name: Pipeline java

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test -B # -B batch mode minder consol output

  deliver-container:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the JAR file with Maven
        run: mvn package -B
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/example-mvc-2:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/example-mvc-2:latest
  
  
  deliver-jar:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the JAR file with Maven
        run: mvn package -B
      - name: Upload the JAR file to GitHub as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-project-jar-file
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deliver-jar
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zipped-project-jar-file
          path: zipped-project-jar-file

      - run: zip -r zipped-project-jar-file.zip zipped-project-jar-file/
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "zipped-project-jar-file.zip"